version: "3.9"
services:

  # php
  app:
    build: ./infra/php
    volumes:
     - ./backend:/work
  
  # nginx
  web:
    image: nginx:1.20-alpine
    ports: 
      - 8080:80
    # ホスト側いあるディレクトリをコンテナ内にマウント
    volumes: 
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work